version: ~> 1.0
language: scala
os: linux
scala:
- 2.12.10
jdk:
- openjdk8
install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 4.0.0
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishMicrosite.sh; fi
stages:
  - name: test
  - name: microsite
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - &lint
      stage: test
      name: "Lint"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Tests for Scala 2.12"
      script: sbt ++$TRAVIS_SCALA_VERSION startDynamodbLocal test dynamodbLocalTestCleanup stopDynamodbLocal
    - &microsite
      stage: microsite
      name: "Generate microsite"
      script: sbt ++$TRAVIS_SCALA_VERSION startDynamodbLocal makeMicrosite stopDynamodbLocal
    - &release
      stage: release
      name: "Release artifacts"
      script: sbt ci-release

    # Cross-build
    - <<: *test
      scala: 2.13.1
      name: "Tests for Scala 2.13"

    # Cross-build
    - <<: *test
      scala: 0.21.0-RC1
      name: "Tests for Scala 3"
